apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydjangoapp1-ingress
  namespace: myapp2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mydjangoapp1.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mydjangoapp1
                port:
                  number: 8091
