apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith-argo-application2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FixedCroissant/vigilant-eureka.git
    targetRevision: HEAD
    #Location in the repo for our necessary kubernetes files.
    #TODO: Change this to work with a proper overlay
    path: monolith-to-microservices/infrastructure/apps/monolith/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
